default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER", "mysql2") %>
  username: root
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV['TEST_MYSQL_HOST'] || 'localhost' %>
  port: <%= ENV['TEST_MYSQL_PORT'] || 3306 %>
  encoding: utf8
  database: turntable_test

test:
  <<: *default
  database: turntable_test
  seq:
    user_seq:
      <<: *default
      database: turntable_user_seq_test
  shards:
    user_shard_1:
      <<: *default
      database: turntable_user_shard_1_test
    user_shard_1_1:
      <<: *default
      database: turntable_user_shard_1_1_test
    user_shard_2:
      <<: *default
      database: turntable_user_shard_2_test
    user_shard_2_1:
      <<: *default
      database: turntable_user_shard_2_1_test
    user_shard_3:
      <<: *default
      database: turntable_user_shard_3_test
    user_shard_3_1:
      <<: *default
      database: turntable_user_shard_3_1_test
    user_shard_4:
      <<: *default
      database: turntable_user_shard_4_test
    user_shard_5:
      <<: *default
      database: turntable_user_shard_5_test
    user_shard_6:
      <<: *default
      database: turntable_user_shard_6_test
